### PR TITLE
Replace `let-alist` by `-let` destructuring

### PR DESCRIPTION
**Pull request by fmdkdd**
Nested `let-alist` calls cause byte-compilation warnings.

The `dash` library is capable of destructuring alists since version
2.13.0, so we use that instead.

@lunaryorn, how do you feel about this refactoring?  I can do the same in the rust JSON parser if you like this solution.

### CODE REVIEW

**Comment by lunaryorn** [comment]
Well syntactically I prefer let-a list to be honest. What warnings does it cause?

**Comment by fmdkdd** [comment]
@lunaryorn These warnings:

```
flycheck-rust.el:103:1:Warning: Unused lexical variable `\.name'
flycheck-rust.el:103:1:Warning: Unused lexical variable `\.kind'
flycheck-rust.el:103:1:Warning: Unused lexical variable `\.src_path'
```

**Comment by lunaryorn** [comment]
What Emacs version is that? I've never seen these warnings in 25.

**Comment by fmdkdd** [comment]
24.5.1.  But I get the same warnings under 25.1.1.

**Comment by lunaryorn** [comment]
@fmdkdd Strangely, though, we get [no warnings](https://travis-ci.org/flycheck/flycheck/jobs/158954570#L834) for `let-alist` in Flycheck itself 😕

**Comment by lunaryorn** [comment]
Ah, maybe that's due to nesting…

**Comment by lunaryorn** [comment]
In any case, if it fixes these warnings go ahead and merge… in Flycheck itself though I'd prefer to keep `let-alist` as long as there are no warnings.

Thanks a lot!

**Comment by fmdkdd** [comment]
@lunaryorn Yep, I had to work around the nesting in flycheck/flycheck#1036  by using `setq`, which I recall you were not in favor of.

**Comment by saruman9** [comment]
After this pull request I have some trouble on Emacs 24.5 and Emacs 25.1 too.
Backtrace:

    Debugger entered--Lisp error: (void-function first)
      first((((kind "bin") (name . "Repo") (src_path . "/home/test/Repo/src/main.rs"))))
      flycheck-rust-find-target("/home/test/Repo/src/main.rs")
      flycheck-rust-setup()

After change:
127:`targets (first targets))]`
127:`targets (car targets))]`
that's all right.

**Comment by lunaryorn** [comment]
@saruman9 Oh, sorry, indeed `first` isn't a good function to use.  I've pushed a fix that replaces it with `car`.

**Comment by fmdkdd** [comment]
@saruman9 Damned, sorry for that.  It didn't occur to me that `first` was not a built-in.

**Pull request merged**
