### PR TITLE
ensure json-read returns cargo manifest as an alist

### PR DESCRIPTION
**Pull request by bassettmb**
`json-read` from json.el can return a non-alist value when `json-object-type` is set to a value distinct from `'alist`. Since the `let-alist` macro expects to receive an alist, `flycheck-rust-get-cargo-targets` will raise a `wrong-type-argument error` and prevent flycheck-rust from loading when `json-object-type` is not `'alist`. (In my case, `json-object-type` was set to `'hash-table` either by default or by some other package.)

### CODE REVIEW

**Comment by guseggert** [comment]
Any way to get this merged, @lunaryorn @fmdkdd ?

**Comment by lunaryorn** [comment]
I'm sorry but I can't help you.   I do not maintain this repository or any other in this organisation since several years ago.

I've unsubscribed from this issue, so please mention me if you'd like me to reply.

**Comment by jcs090218** [comment]
Are there maintainers for this package? I would love to take over the maintenance if that's the case. Mentioning @lebensterben since he showed interest in maintaining this package as well (from gitter).

Any thoughts? @cpitclaudel @fmdkdd

**Comment by lebensterben** [comment]
I'm proficient in both elisp and rust. If new maintainers are needed, I can take the job.

**Comment by jcs090218** [comment]
@cpitclaudel Friendly ping! :)

**Comment by bbatsov** [comment]
> Are there maintainers for this package? I would love to take over the maintenance if that's the case. Mentioning @lebensterben since he showed interest in maintaining this package as well (from gitter).

@jcs090218 Seems I'm the primary maintainer of Flycheck these days, and I've just added you to the `flycheck-rust` team. I don't know much about Rust linters, but I'm here as well if needed for something.

**Comment by jcs090218** [comment]
@bbatsov Thank you!

**Pull request merged**
